// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "avgpool_7x7_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic avgpool_7x7_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic avgpool_7x7_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> avgpool_7x7_1::ap_ST_fsm_state1 = "1";
const sc_lv<6> avgpool_7x7_1::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<6> avgpool_7x7_1::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<6> avgpool_7x7_1::ap_ST_fsm_pp0_stage2 = "1000";
const sc_lv<6> avgpool_7x7_1::ap_ST_fsm_pp0_stage3 = "10000";
const sc_lv<6> avgpool_7x7_1::ap_ST_fsm_state9 = "100000";
const bool avgpool_7x7_1::ap_const_boolean_1 = true;
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_1 = "1";
const bool avgpool_7x7_1::ap_const_boolean_0 = false;
const sc_lv<1> avgpool_7x7_1::ap_const_lv1_0 = "0";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_2 = "10";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_3 = "11";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_4 = "100";
const sc_lv<1> avgpool_7x7_1::ap_const_lv1_1 = "1";
const sc_lv<14> avgpool_7x7_1::ap_const_lv14_0 = "00000000000000";
const sc_lv<4> avgpool_7x7_1::ap_const_lv4_1 = "1";
const sc_lv<4> avgpool_7x7_1::ap_const_lv4_8 = "1000";
const sc_lv<3> avgpool_7x7_1::ap_const_lv3_0 = "000";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_1 = "1";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_2 = "10";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_3 = "11";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_4 = "100";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_5 = "101";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_6 = "110";
const sc_lv<8> avgpool_7x7_1::ap_const_lv8_7 = "111";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_E = "1110";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_D = "1101";
const sc_lv<14> avgpool_7x7_1::ap_const_lv14_1FFF = "1111111111111";
const sc_lv<14> avgpool_7x7_1::ap_const_lv14_2000 = "10000000000000";
const sc_lv<32> avgpool_7x7_1::ap_const_lv32_5 = "101";
const sc_lv<15> avgpool_7x7_1::ap_const_lv15_0 = "000000000000000";
const sc_lv<11> avgpool_7x7_1::ap_const_lv11_0 = "00000000000";

avgpool_7x7_1::avgpool_7x7_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    p_Val2_22_sum_engine_1_fu_163 = new sum_engine_1("p_Val2_22_sum_engine_1_fu_163");
    p_Val2_22_sum_engine_1_fu_163->ap_ready(p_Val2_22_sum_engine_1_fu_163_ap_ready);
    p_Val2_22_sum_engine_1_fu_163->t0_V(buf_V_load_reg_465);
    p_Val2_22_sum_engine_1_fu_163->t1_V(buf_V_load_1_reg_470);
    p_Val2_22_sum_engine_1_fu_163->t2_V(buf_V_load_2_reg_485);
    p_Val2_22_sum_engine_1_fu_163->t3_V(buf_V_load_3_reg_490);
    p_Val2_22_sum_engine_1_fu_163->t4_V(buf_V_load_4_reg_500);
    p_Val2_22_sum_engine_1_fu_163->t5_V(buf_V_load_5_reg_505);
    p_Val2_22_sum_engine_1_fu_163->t6_V(buf_V_load_6_reg_515);
    p_Val2_22_sum_engine_1_fu_163->ap_return(p_Val2_22_sum_engine_1_fu_163_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln210_1_fu_202_p2);
    sensitive << ( add_ln210_fu_196_p2 );

    SC_METHOD(thread_add_ln210_2_fu_213_p2);
    sensitive << ( add_ln210_fu_196_p2 );

    SC_METHOD(thread_add_ln210_3_fu_224_p2);
    sensitive << ( add_ln210_reg_436 );

    SC_METHOD(thread_add_ln210_4_fu_234_p2);
    sensitive << ( add_ln210_reg_436 );

    SC_METHOD(thread_add_ln210_5_fu_244_p2);
    sensitive << ( add_ln210_reg_436 );

    SC_METHOD(thread_add_ln210_6_fu_254_p2);
    sensitive << ( add_ln210_reg_436 );

    SC_METHOD(thread_add_ln210_7_fu_264_p2);
    sensitive << ( add_ln210_reg_436 );

    SC_METHOD(thread_add_ln210_fu_196_p2);
    sensitive << ( zext_ln210_fu_180_p1 );
    sensitive << ( zext_ln210_1_fu_192_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state8_pp0_stage2_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln208_fu_174_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_row_0_phi_fu_155_p4);
    sensitive << ( row_0_reg_151 );
    sensitive << ( icmp_ln208_reg_432 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( row_reg_510 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_buf_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln210_2_fu_208_p1 );
    sensitive << ( sext_ln210_1_fu_229_p1 );
    sensitive << ( sext_ln210_3_fu_249_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sext_ln210_5_fu_269_p1 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_buf_V_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( sext_ln210_fu_219_p1 );
    sensitive << ( sext_ln210_2_fu_239_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( sext_ln210_4_fu_259_p1 );

    SC_METHOD(thread_buf_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_buf_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_icmp_ln208_fu_174_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_row_0_phi_fu_155_p4 );

    SC_METHOD(thread_lhs_V_fu_280_p1);
    sensitive << ( p_Val2_21_reg_139 );

    SC_METHOD(thread_or_ln340_39_fu_338_p2);
    sensitive << ( p_Result_10_fu_306_p3 );
    sensitive << ( xor_ln340_fu_332_p2 );

    SC_METHOD(thread_p_Result_10_fu_306_p3);
    sensitive << ( sum_V_fu_301_p2 );

    SC_METHOD(thread_p_Result_s_fu_293_p3);
    sensitive << ( ret_V_fu_287_p2 );

    SC_METHOD(thread_r_V_fu_424_p3);
    sensitive << ( tmp_1367_fu_372_p3 );
    sensitive << ( sub_ln1148_1_fu_400_p2 );
    sensitive << ( zext_ln1148_fu_420_p1 );

    SC_METHOD(thread_ret_V_fu_287_p2);
    sensitive << ( lhs_V_fu_280_p1 );
    sensitive << ( rhs_V_fu_284_p1 );

    SC_METHOD(thread_rhs_V_fu_284_p1);
    sensitive << ( p_Val2_22_reg_520 );

    SC_METHOD(thread_row_fu_274_p2);
    sensitive << ( row_0_reg_151 );

    SC_METHOD(thread_select_ln340_526_fu_360_p3);
    sensitive << ( or_ln340_39_fu_338_p2 );
    sensitive << ( select_ln340_fu_344_p3 );
    sensitive << ( select_ln388_fu_352_p3 );

    SC_METHOD(thread_select_ln340_fu_344_p3);
    sensitive << ( sum_V_fu_301_p2 );
    sensitive << ( xor_ln340_317_fu_326_p2 );

    SC_METHOD(thread_select_ln388_fu_352_p3);
    sensitive << ( sum_V_fu_301_p2 );
    sensitive << ( underflow_fu_320_p2 );

    SC_METHOD(thread_sext_ln1148_1_fu_416_p1);
    sensitive << ( trunc_ln1148_1_fu_406_p4 );

    SC_METHOD(thread_sext_ln1148_fu_368_p1);
    sensitive << ( p_Val2_21_reg_139 );

    SC_METHOD(thread_sext_ln210_1_fu_229_p1);
    sensitive << ( add_ln210_3_fu_224_p2 );

    SC_METHOD(thread_sext_ln210_2_fu_239_p1);
    sensitive << ( add_ln210_4_fu_234_p2 );

    SC_METHOD(thread_sext_ln210_3_fu_249_p1);
    sensitive << ( add_ln210_5_fu_244_p2 );

    SC_METHOD(thread_sext_ln210_4_fu_259_p1);
    sensitive << ( add_ln210_6_fu_254_p2 );

    SC_METHOD(thread_sext_ln210_5_fu_269_p1);
    sensitive << ( add_ln210_7_fu_264_p2 );

    SC_METHOD(thread_sext_ln210_fu_219_p1);
    sensitive << ( add_ln210_2_fu_213_p2 );

    SC_METHOD(thread_sub_ln1148_1_fu_400_p2);
    sensitive << ( zext_ln1148_1_fu_396_p1 );

    SC_METHOD(thread_sub_ln1148_fu_380_p2);
    sensitive << ( sext_ln1148_fu_368_p1 );

    SC_METHOD(thread_sum_V_fu_301_p2);
    sensitive << ( p_Val2_21_reg_139 );
    sensitive << ( p_Val2_22_reg_520 );

    SC_METHOD(thread_tmp_1367_fu_372_p3);
    sensitive << ( p_Val2_21_reg_139 );

    SC_METHOD(thread_tmp_491_fu_184_p3);
    sensitive << ( ap_phi_mux_row_0_phi_fu_155_p4 );

    SC_METHOD(thread_tmp_s_fu_386_p4);
    sensitive << ( sub_ln1148_fu_380_p2 );

    SC_METHOD(thread_trunc_ln1148_1_fu_406_p4);
    sensitive << ( p_Val2_21_reg_139 );

    SC_METHOD(thread_underflow_fu_320_p2);
    sensitive << ( p_Result_s_fu_293_p3 );
    sensitive << ( xor_ln786_10_fu_314_p2 );

    SC_METHOD(thread_xor_ln340_317_fu_326_p2);
    sensitive << ( p_Result_10_fu_306_p3 );
    sensitive << ( p_Result_s_fu_293_p3 );

    SC_METHOD(thread_xor_ln340_fu_332_p2);
    sensitive << ( p_Result_s_fu_293_p3 );

    SC_METHOD(thread_xor_ln786_10_fu_314_p2);
    sensitive << ( p_Result_10_fu_306_p3 );

    SC_METHOD(thread_zext_ln1148_1_fu_396_p1);
    sensitive << ( tmp_s_fu_386_p4 );

    SC_METHOD(thread_zext_ln1148_fu_420_p1);
    sensitive << ( sext_ln1148_1_fu_416_p1 );

    SC_METHOD(thread_zext_ln210_1_fu_192_p1);
    sensitive << ( tmp_491_fu_184_p3 );

    SC_METHOD(thread_zext_ln210_2_fu_208_p1);
    sensitive << ( add_ln210_1_fu_202_p2 );

    SC_METHOD(thread_zext_ln210_fu_180_p1);
    sensitive << ( ap_phi_mux_row_0_phi_fu_155_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln208_fu_174_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );

    ap_CS_fsm = "000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "avgpool_7x7_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, buf_V_address0, "(port)buf_V_address0");
    sc_trace(mVcdFile, buf_V_ce0, "(port)buf_V_ce0");
    sc_trace(mVcdFile, buf_V_q0, "(port)buf_V_q0");
    sc_trace(mVcdFile, buf_V_address1, "(port)buf_V_address1");
    sc_trace(mVcdFile, buf_V_ce1, "(port)buf_V_ce1");
    sc_trace(mVcdFile, buf_V_q1, "(port)buf_V_q1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_Val2_21_reg_139, "p_Val2_21_reg_139");
    sc_trace(mVcdFile, row_0_reg_151, "row_0_reg_151");
    sc_trace(mVcdFile, icmp_ln208_fu_174_p2, "icmp_ln208_fu_174_p2");
    sc_trace(mVcdFile, icmp_ln208_reg_432, "icmp_ln208_reg_432");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln208_reg_432_pp0_iter1_reg, "icmp_ln208_reg_432_pp0_iter1_reg");
    sc_trace(mVcdFile, add_ln210_fu_196_p2, "add_ln210_fu_196_p2");
    sc_trace(mVcdFile, add_ln210_reg_436, "add_ln210_reg_436");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter1, "ap_block_state7_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, buf_V_load_reg_465, "buf_V_load_reg_465");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, buf_V_load_1_reg_470, "buf_V_load_1_reg_470");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage2_iter0, "ap_block_state4_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage2_iter1, "ap_block_state8_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, buf_V_load_2_reg_485, "buf_V_load_2_reg_485");
    sc_trace(mVcdFile, buf_V_load_3_reg_490, "buf_V_load_3_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage3_iter0, "ap_block_state5_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, buf_V_load_4_reg_500, "buf_V_load_4_reg_500");
    sc_trace(mVcdFile, buf_V_load_5_reg_505, "buf_V_load_5_reg_505");
    sc_trace(mVcdFile, row_fu_274_p2, "row_fu_274_p2");
    sc_trace(mVcdFile, row_reg_510, "row_reg_510");
    sc_trace(mVcdFile, buf_V_load_6_reg_515, "buf_V_load_6_reg_515");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, p_Val2_22_sum_engine_1_fu_163_ap_return, "p_Val2_22_sum_engine_1_fu_163_ap_return");
    sc_trace(mVcdFile, p_Val2_22_reg_520, "p_Val2_22_reg_520");
    sc_trace(mVcdFile, select_ln340_526_fu_360_p3, "select_ln340_526_fu_360_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, p_Val2_22_sum_engine_1_fu_163_ap_ready, "p_Val2_22_sum_engine_1_fu_163_ap_ready");
    sc_trace(mVcdFile, ap_phi_mux_row_0_phi_fu_155_p4, "ap_phi_mux_row_0_phi_fu_155_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, zext_ln210_2_fu_208_p1, "zext_ln210_2_fu_208_p1");
    sc_trace(mVcdFile, sext_ln210_fu_219_p1, "sext_ln210_fu_219_p1");
    sc_trace(mVcdFile, sext_ln210_1_fu_229_p1, "sext_ln210_1_fu_229_p1");
    sc_trace(mVcdFile, sext_ln210_2_fu_239_p1, "sext_ln210_2_fu_239_p1");
    sc_trace(mVcdFile, sext_ln210_3_fu_249_p1, "sext_ln210_3_fu_249_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, sext_ln210_4_fu_259_p1, "sext_ln210_4_fu_259_p1");
    sc_trace(mVcdFile, sext_ln210_5_fu_269_p1, "sext_ln210_5_fu_269_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, tmp_491_fu_184_p3, "tmp_491_fu_184_p3");
    sc_trace(mVcdFile, zext_ln210_fu_180_p1, "zext_ln210_fu_180_p1");
    sc_trace(mVcdFile, zext_ln210_1_fu_192_p1, "zext_ln210_1_fu_192_p1");
    sc_trace(mVcdFile, add_ln210_1_fu_202_p2, "add_ln210_1_fu_202_p2");
    sc_trace(mVcdFile, add_ln210_2_fu_213_p2, "add_ln210_2_fu_213_p2");
    sc_trace(mVcdFile, add_ln210_3_fu_224_p2, "add_ln210_3_fu_224_p2");
    sc_trace(mVcdFile, add_ln210_4_fu_234_p2, "add_ln210_4_fu_234_p2");
    sc_trace(mVcdFile, add_ln210_5_fu_244_p2, "add_ln210_5_fu_244_p2");
    sc_trace(mVcdFile, add_ln210_6_fu_254_p2, "add_ln210_6_fu_254_p2");
    sc_trace(mVcdFile, add_ln210_7_fu_264_p2, "add_ln210_7_fu_264_p2");
    sc_trace(mVcdFile, lhs_V_fu_280_p1, "lhs_V_fu_280_p1");
    sc_trace(mVcdFile, rhs_V_fu_284_p1, "rhs_V_fu_284_p1");
    sc_trace(mVcdFile, ret_V_fu_287_p2, "ret_V_fu_287_p2");
    sc_trace(mVcdFile, sum_V_fu_301_p2, "sum_V_fu_301_p2");
    sc_trace(mVcdFile, p_Result_10_fu_306_p3, "p_Result_10_fu_306_p3");
    sc_trace(mVcdFile, p_Result_s_fu_293_p3, "p_Result_s_fu_293_p3");
    sc_trace(mVcdFile, xor_ln786_10_fu_314_p2, "xor_ln786_10_fu_314_p2");
    sc_trace(mVcdFile, xor_ln340_fu_332_p2, "xor_ln340_fu_332_p2");
    sc_trace(mVcdFile, xor_ln340_317_fu_326_p2, "xor_ln340_317_fu_326_p2");
    sc_trace(mVcdFile, underflow_fu_320_p2, "underflow_fu_320_p2");
    sc_trace(mVcdFile, or_ln340_39_fu_338_p2, "or_ln340_39_fu_338_p2");
    sc_trace(mVcdFile, select_ln340_fu_344_p3, "select_ln340_fu_344_p3");
    sc_trace(mVcdFile, select_ln388_fu_352_p3, "select_ln388_fu_352_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, sext_ln1148_fu_368_p1, "sext_ln1148_fu_368_p1");
    sc_trace(mVcdFile, sub_ln1148_fu_380_p2, "sub_ln1148_fu_380_p2");
    sc_trace(mVcdFile, tmp_s_fu_386_p4, "tmp_s_fu_386_p4");
    sc_trace(mVcdFile, zext_ln1148_1_fu_396_p1, "zext_ln1148_1_fu_396_p1");
    sc_trace(mVcdFile, trunc_ln1148_1_fu_406_p4, "trunc_ln1148_1_fu_406_p4");
    sc_trace(mVcdFile, sext_ln1148_1_fu_416_p1, "sext_ln1148_1_fu_416_p1");
    sc_trace(mVcdFile, tmp_1367_fu_372_p3, "tmp_1367_fu_372_p3");
    sc_trace(mVcdFile, sub_ln1148_1_fu_400_p2, "sub_ln1148_1_fu_400_p2");
    sc_trace(mVcdFile, zext_ln1148_fu_420_p1, "zext_ln1148_fu_420_p1");
    sc_trace(mVcdFile, r_V_fu_424_p3, "r_V_fu_424_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

avgpool_7x7_1::~avgpool_7x7_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete p_Val2_22_sum_engine_1_fu_163;
}

void avgpool_7x7_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln208_reg_432_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_21_reg_139 = select_ln340_526_fu_360_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_21_reg_139 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln208_reg_432.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        row_0_reg_151 = row_reg_510.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        row_0_reg_151 = ap_const_lv4_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln208_fu_174_p2.read(), ap_const_lv1_0))) {
        add_ln210_reg_436 = add_ln210_fu_196_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_return = r_V_fu_424_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln208_reg_432.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        buf_V_load_1_reg_470 = buf_V_q1.read();
        buf_V_load_reg_465 = buf_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln208_reg_432.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        buf_V_load_2_reg_485 = buf_V_q0.read();
        buf_V_load_3_reg_490 = buf_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln208_reg_432.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        buf_V_load_4_reg_500 = buf_V_q0.read();
        buf_V_load_5_reg_505 = buf_V_q1.read();
        row_reg_510 = row_fu_274_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln208_reg_432.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        buf_V_load_6_reg_515 = buf_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln208_reg_432 = icmp_ln208_fu_174_p2.read();
        icmp_ln208_reg_432_pp0_iter1_reg = icmp_ln208_reg_432.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln208_reg_432_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_22_reg_520 = p_Val2_22_sum_engine_1_fu_163_ap_return.read();
    }
}

void avgpool_7x7_1::thread_add_ln210_1_fu_202_p2() {
    add_ln210_1_fu_202_p2 = (!add_ln210_fu_196_p2.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_fu_196_p2.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void avgpool_7x7_1::thread_add_ln210_2_fu_213_p2() {
    add_ln210_2_fu_213_p2 = (!add_ln210_fu_196_p2.read().is_01() || !ap_const_lv8_2.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_fu_196_p2.read()) + sc_biguint<8>(ap_const_lv8_2));
}

void avgpool_7x7_1::thread_add_ln210_3_fu_224_p2() {
    add_ln210_3_fu_224_p2 = (!add_ln210_reg_436.read().is_01() || !ap_const_lv8_3.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_reg_436.read()) + sc_biguint<8>(ap_const_lv8_3));
}

void avgpool_7x7_1::thread_add_ln210_4_fu_234_p2() {
    add_ln210_4_fu_234_p2 = (!add_ln210_reg_436.read().is_01() || !ap_const_lv8_4.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_reg_436.read()) + sc_biguint<8>(ap_const_lv8_4));
}

void avgpool_7x7_1::thread_add_ln210_5_fu_244_p2() {
    add_ln210_5_fu_244_p2 = (!add_ln210_reg_436.read().is_01() || !ap_const_lv8_5.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_reg_436.read()) + sc_biguint<8>(ap_const_lv8_5));
}

void avgpool_7x7_1::thread_add_ln210_6_fu_254_p2() {
    add_ln210_6_fu_254_p2 = (!add_ln210_reg_436.read().is_01() || !ap_const_lv8_6.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_reg_436.read()) + sc_biguint<8>(ap_const_lv8_6));
}

void avgpool_7x7_1::thread_add_ln210_7_fu_264_p2() {
    add_ln210_7_fu_264_p2 = (!add_ln210_reg_436.read().is_01() || !ap_const_lv8_7.is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln210_reg_436.read()) + sc_biguint<8>(ap_const_lv8_7));
}

void avgpool_7x7_1::thread_add_ln210_fu_196_p2() {
    add_ln210_fu_196_p2 = (!zext_ln210_fu_180_p1.read().is_01() || !zext_ln210_1_fu_192_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln210_fu_180_p1.read()) + sc_biguint<8>(zext_ln210_1_fu_192_p1.read()));
}

void avgpool_7x7_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void avgpool_7x7_1::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void avgpool_7x7_1::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[3];
}

void avgpool_7x7_1::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[4];
}

void avgpool_7x7_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void avgpool_7x7_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[5];
}

void avgpool_7x7_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state4_pp0_stage2_iter0() {
    ap_block_state4_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state5_pp0_stage3_iter0() {
    ap_block_state5_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state7_pp0_stage1_iter1() {
    ap_block_state7_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_block_state8_pp0_stage2_iter1() {
    ap_block_state8_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void avgpool_7x7_1::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln208_fu_174_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void avgpool_7x7_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_ap_phi_mux_row_0_phi_fu_155_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(icmp_ln208_reg_432.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_row_0_phi_fu_155_p4 = row_reg_510.read();
    } else {
        ap_phi_mux_row_0_phi_fu_155_p4 = row_0_reg_151.read();
    }
}

void avgpool_7x7_1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_buf_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            buf_V_address0 =  (sc_lv<7>) (sext_ln210_5_fu_269_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            buf_V_address0 =  (sc_lv<7>) (sext_ln210_3_fu_249_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            buf_V_address0 =  (sc_lv<7>) (sext_ln210_1_fu_229_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            buf_V_address0 =  (sc_lv<7>) (zext_ln210_2_fu_208_p1.read());
        } else {
            buf_V_address0 = "XXXXXXX";
        }
    } else {
        buf_V_address0 = "XXXXXXX";
    }
}

void avgpool_7x7_1::thread_buf_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            buf_V_address1 =  (sc_lv<7>) (sext_ln210_4_fu_259_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            buf_V_address1 =  (sc_lv<7>) (sext_ln210_2_fu_239_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            buf_V_address1 =  (sc_lv<7>) (sext_ln210_fu_219_p1.read());
        } else {
            buf_V_address1 = "XXXXXXX";
        }
    } else {
        buf_V_address1 = "XXXXXXX";
    }
}

void avgpool_7x7_1::thread_buf_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())))) {
        buf_V_ce0 = ap_const_logic_1;
    } else {
        buf_V_ce0 = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_buf_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())))) {
        buf_V_ce1 = ap_const_logic_1;
    } else {
        buf_V_ce1 = ap_const_logic_0;
    }
}

void avgpool_7x7_1::thread_icmp_ln208_fu_174_p2() {
    icmp_ln208_fu_174_p2 = (!ap_phi_mux_row_0_phi_fu_155_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_row_0_phi_fu_155_p4.read() == ap_const_lv4_8);
}

void avgpool_7x7_1::thread_lhs_V_fu_280_p1() {
    lhs_V_fu_280_p1 = esl_sext<15,14>(p_Val2_21_reg_139.read());
}

void avgpool_7x7_1::thread_or_ln340_39_fu_338_p2() {
    or_ln340_39_fu_338_p2 = (p_Result_10_fu_306_p3.read() | xor_ln340_fu_332_p2.read());
}

void avgpool_7x7_1::thread_p_Result_10_fu_306_p3() {
    p_Result_10_fu_306_p3 = sum_V_fu_301_p2.read().range(13, 13);
}

void avgpool_7x7_1::thread_p_Result_s_fu_293_p3() {
    p_Result_s_fu_293_p3 = ret_V_fu_287_p2.read().range(14, 14);
}

void avgpool_7x7_1::thread_r_V_fu_424_p3() {
    r_V_fu_424_p3 = (!tmp_1367_fu_372_p3.read()[0].is_01())? sc_lv<11>(): ((tmp_1367_fu_372_p3.read()[0].to_bool())? sub_ln1148_1_fu_400_p2.read(): zext_ln1148_fu_420_p1.read());
}

void avgpool_7x7_1::thread_ret_V_fu_287_p2() {
    ret_V_fu_287_p2 = (!lhs_V_fu_280_p1.read().is_01() || !rhs_V_fu_284_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(lhs_V_fu_280_p1.read()) + sc_bigint<15>(rhs_V_fu_284_p1.read()));
}

void avgpool_7x7_1::thread_rhs_V_fu_284_p1() {
    rhs_V_fu_284_p1 = esl_sext<15,14>(p_Val2_22_reg_520.read());
}

void avgpool_7x7_1::thread_row_fu_274_p2() {
    row_fu_274_p2 = (!row_0_reg_151.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_0_reg_151.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void avgpool_7x7_1::thread_select_ln340_526_fu_360_p3() {
    select_ln340_526_fu_360_p3 = (!or_ln340_39_fu_338_p2.read()[0].is_01())? sc_lv<14>(): ((or_ln340_39_fu_338_p2.read()[0].to_bool())? select_ln340_fu_344_p3.read(): select_ln388_fu_352_p3.read());
}

void avgpool_7x7_1::thread_select_ln340_fu_344_p3() {
    select_ln340_fu_344_p3 = (!xor_ln340_317_fu_326_p2.read()[0].is_01())? sc_lv<14>(): ((xor_ln340_317_fu_326_p2.read()[0].to_bool())? ap_const_lv14_1FFF: sum_V_fu_301_p2.read());
}

void avgpool_7x7_1::thread_select_ln388_fu_352_p3() {
    select_ln388_fu_352_p3 = (!underflow_fu_320_p2.read()[0].is_01())? sc_lv<14>(): ((underflow_fu_320_p2.read()[0].to_bool())? ap_const_lv14_2000: sum_V_fu_301_p2.read());
}

void avgpool_7x7_1::thread_sext_ln1148_1_fu_416_p1() {
    sext_ln1148_1_fu_416_p1 = esl_sext<10,9>(trunc_ln1148_1_fu_406_p4.read());
}

void avgpool_7x7_1::thread_sext_ln1148_fu_368_p1() {
    sext_ln1148_fu_368_p1 = esl_sext<15,14>(p_Val2_21_reg_139.read());
}

void avgpool_7x7_1::thread_sext_ln210_1_fu_229_p1() {
    sext_ln210_1_fu_229_p1 = esl_sext<64,8>(add_ln210_3_fu_224_p2.read());
}

void avgpool_7x7_1::thread_sext_ln210_2_fu_239_p1() {
    sext_ln210_2_fu_239_p1 = esl_sext<64,8>(add_ln210_4_fu_234_p2.read());
}

void avgpool_7x7_1::thread_sext_ln210_3_fu_249_p1() {
    sext_ln210_3_fu_249_p1 = esl_sext<64,8>(add_ln210_5_fu_244_p2.read());
}

void avgpool_7x7_1::thread_sext_ln210_4_fu_259_p1() {
    sext_ln210_4_fu_259_p1 = esl_sext<64,8>(add_ln210_6_fu_254_p2.read());
}

void avgpool_7x7_1::thread_sext_ln210_5_fu_269_p1() {
    sext_ln210_5_fu_269_p1 = esl_sext<64,8>(add_ln210_7_fu_264_p2.read());
}

void avgpool_7x7_1::thread_sext_ln210_fu_219_p1() {
    sext_ln210_fu_219_p1 = esl_sext<64,8>(add_ln210_2_fu_213_p2.read());
}

void avgpool_7x7_1::thread_sub_ln1148_1_fu_400_p2() {
    sub_ln1148_1_fu_400_p2 = (!ap_const_lv11_0.is_01() || !zext_ln1148_1_fu_396_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_0) - sc_biguint<11>(zext_ln1148_1_fu_396_p1.read()));
}

void avgpool_7x7_1::thread_sub_ln1148_fu_380_p2() {
    sub_ln1148_fu_380_p2 = (!ap_const_lv15_0.is_01() || !sext_ln1148_fu_368_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_0) - sc_bigint<15>(sext_ln1148_fu_368_p1.read()));
}

void avgpool_7x7_1::thread_sum_V_fu_301_p2() {
    sum_V_fu_301_p2 = (!p_Val2_22_reg_520.read().is_01() || !p_Val2_21_reg_139.read().is_01())? sc_lv<14>(): (sc_bigint<14>(p_Val2_22_reg_520.read()) + sc_bigint<14>(p_Val2_21_reg_139.read()));
}

void avgpool_7x7_1::thread_tmp_1367_fu_372_p3() {
    tmp_1367_fu_372_p3 = p_Val2_21_reg_139.read().range(13, 13);
}

void avgpool_7x7_1::thread_tmp_491_fu_184_p3() {
    tmp_491_fu_184_p3 = esl_concat<4,3>(ap_phi_mux_row_0_phi_fu_155_p4.read(), ap_const_lv3_0);
}

void avgpool_7x7_1::thread_tmp_s_fu_386_p4() {
    tmp_s_fu_386_p4 = sub_ln1148_fu_380_p2.read().range(14, 5);
}

void avgpool_7x7_1::thread_trunc_ln1148_1_fu_406_p4() {
    trunc_ln1148_1_fu_406_p4 = p_Val2_21_reg_139.read().range(13, 5);
}

void avgpool_7x7_1::thread_underflow_fu_320_p2() {
    underflow_fu_320_p2 = (p_Result_s_fu_293_p3.read() & xor_ln786_10_fu_314_p2.read());
}

void avgpool_7x7_1::thread_xor_ln340_317_fu_326_p2() {
    xor_ln340_317_fu_326_p2 = (p_Result_s_fu_293_p3.read() ^ p_Result_10_fu_306_p3.read());
}

void avgpool_7x7_1::thread_xor_ln340_fu_332_p2() {
    xor_ln340_fu_332_p2 = (p_Result_s_fu_293_p3.read() ^ ap_const_lv1_1);
}

void avgpool_7x7_1::thread_xor_ln786_10_fu_314_p2() {
    xor_ln786_10_fu_314_p2 = (p_Result_10_fu_306_p3.read() ^ ap_const_lv1_1);
}

void avgpool_7x7_1::thread_zext_ln1148_1_fu_396_p1() {
    zext_ln1148_1_fu_396_p1 = esl_zext<11,10>(tmp_s_fu_386_p4.read());
}

void avgpool_7x7_1::thread_zext_ln1148_fu_420_p1() {
    zext_ln1148_fu_420_p1 = esl_zext<11,10>(sext_ln1148_1_fu_416_p1.read());
}

void avgpool_7x7_1::thread_zext_ln210_1_fu_192_p1() {
    zext_ln210_1_fu_192_p1 = esl_zext<8,7>(tmp_491_fu_184_p3.read());
}

void avgpool_7x7_1::thread_zext_ln210_2_fu_208_p1() {
    zext_ln210_2_fu_208_p1 = esl_zext<64,8>(add_ln210_1_fu_202_p2.read());
}

void avgpool_7x7_1::thread_zext_ln210_fu_180_p1() {
    zext_ln210_fu_180_p1 = esl_zext<8,4>(ap_phi_mux_row_0_phi_fu_155_p4.read());
}

void avgpool_7x7_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln208_fu_174_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln208_fu_174_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

