// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_engine_32_HH_
#define _compute_engine_32_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "compute_engine_32bkb.h"

namespace ap_rtl {

struct compute_engine_32 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > ap_ce;
    sc_in< sc_lv<32> > b_V;
    sc_in< sc_lv<32> > w_V;
    sc_out< sc_lv<6> > ap_return;


    // Module declarations
    compute_engine_32(sc_module_name name);
    SC_HAS_PROCESS(compute_engine_32);

    ~compute_engine_32();

    sc_trace_file* mVcdFile;

    compute_engine_32bkb* lut16_V_U;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<4> > lut16_V_address0;
    sc_signal< sc_logic > lut16_V_ce0;
    sc_signal< sc_lv<3> > lut16_V_q0;
    sc_signal< sc_lv<4> > lut16_V_address1;
    sc_signal< sc_logic > lut16_V_ce1;
    sc_signal< sc_lv<3> > lut16_V_q1;
    sc_signal< sc_lv<4> > lut16_V_address2;
    sc_signal< sc_logic > lut16_V_ce2;
    sc_signal< sc_lv<3> > lut16_V_q2;
    sc_signal< sc_lv<4> > lut16_V_address3;
    sc_signal< sc_logic > lut16_V_ce3;
    sc_signal< sc_lv<3> > lut16_V_q3;
    sc_signal< sc_lv<4> > lut16_V_address4;
    sc_signal< sc_logic > lut16_V_ce4;
    sc_signal< sc_lv<3> > lut16_V_q4;
    sc_signal< sc_lv<4> > lut16_V_address5;
    sc_signal< sc_logic > lut16_V_ce5;
    sc_signal< sc_lv<3> > lut16_V_q5;
    sc_signal< sc_lv<4> > lut16_V_address6;
    sc_signal< sc_logic > lut16_V_ce6;
    sc_signal< sc_lv<3> > lut16_V_q6;
    sc_signal< sc_lv<4> > lut16_V_address7;
    sc_signal< sc_logic > lut16_V_ce7;
    sc_signal< sc_lv<3> > lut16_V_q7;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_lv<64> > zext_ln18_fu_175_p1;
    sc_signal< sc_lv<64> > zext_ln18_1_fu_190_p1;
    sc_signal< sc_lv<64> > zext_ln19_fu_205_p1;
    sc_signal< sc_lv<64> > zext_ln19_1_fu_220_p1;
    sc_signal< sc_lv<64> > zext_ln20_fu_235_p1;
    sc_signal< sc_lv<64> > zext_ln20_1_fu_250_p1;
    sc_signal< sc_lv<64> > zext_ln21_fu_265_p1;
    sc_signal< sc_lv<64> > zext_ln21_1_fu_280_p1;
    sc_signal< sc_lv<32> > xor_ln769_fu_159_p2;
    sc_signal< sc_lv<32> > r_V_fu_165_p2;
    sc_signal< sc_lv<4> > trunc_ln681_fu_171_p1;
    sc_signal< sc_lv<4> > p_Result_s_fu_180_p4;
    sc_signal< sc_lv<4> > p_Result_1_fu_195_p4;
    sc_signal< sc_lv<4> > p_Result_2_fu_210_p4;
    sc_signal< sc_lv<4> > p_Result_3_fu_225_p4;
    sc_signal< sc_lv<4> > p_Result_4_fu_240_p4;
    sc_signal< sc_lv<4> > p_Result_5_fu_255_p4;
    sc_signal< sc_lv<4> > p_Result_6_fu_270_p4;
    sc_signal< sc_lv<4> > zext_ln215_fu_285_p1;
    sc_signal< sc_lv<4> > zext_ln215_1_fu_289_p1;
    sc_signal< sc_lv<4> > zext_ln215_2_fu_299_p1;
    sc_signal< sc_lv<4> > zext_ln215_3_fu_303_p1;
    sc_signal< sc_lv<4> > zext_ln215_4_fu_313_p1;
    sc_signal< sc_lv<4> > zext_ln215_5_fu_317_p1;
    sc_signal< sc_lv<4> > zext_ln215_6_fu_327_p1;
    sc_signal< sc_lv<4> > zext_ln215_7_fu_331_p1;
    sc_signal< sc_lv<4> > add0_V_fu_293_p2;
    sc_signal< sc_lv<4> > add1_V_fu_307_p2;
    sc_signal< sc_lv<5> > lhs_V_fu_341_p1;
    sc_signal< sc_lv<5> > rhs_V_fu_345_p1;
    sc_signal< sc_lv<4> > add2_V_fu_321_p2;
    sc_signal< sc_lv<4> > add3_V_fu_335_p2;
    sc_signal< sc_lv<5> > lhs_V_4_fu_355_p1;
    sc_signal< sc_lv<5> > rhs_V_5_fu_359_p1;
    sc_signal< sc_lv<5> > ret_V_5_fu_349_p2;
    sc_signal< sc_lv<5> > ret_V_6_fu_363_p2;
    sc_signal< sc_lv<6> > lhs_V_5_fu_369_p1;
    sc_signal< sc_lv<6> > rhs_V_6_fu_373_p1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0_0to0;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_reset_start_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1F;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add0_V_fu_293_p2();
    void thread_add1_V_fu_307_p2();
    void thread_add2_V_fu_321_p2();
    void thread_add3_V_fu_335_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to0();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_reset_start_pp0();
    void thread_ap_return();
    void thread_lhs_V_4_fu_355_p1();
    void thread_lhs_V_5_fu_369_p1();
    void thread_lhs_V_fu_341_p1();
    void thread_lut16_V_address0();
    void thread_lut16_V_address1();
    void thread_lut16_V_address2();
    void thread_lut16_V_address3();
    void thread_lut16_V_address4();
    void thread_lut16_V_address5();
    void thread_lut16_V_address6();
    void thread_lut16_V_address7();
    void thread_lut16_V_ce0();
    void thread_lut16_V_ce1();
    void thread_lut16_V_ce2();
    void thread_lut16_V_ce3();
    void thread_lut16_V_ce4();
    void thread_lut16_V_ce5();
    void thread_lut16_V_ce6();
    void thread_lut16_V_ce7();
    void thread_p_Result_1_fu_195_p4();
    void thread_p_Result_2_fu_210_p4();
    void thread_p_Result_3_fu_225_p4();
    void thread_p_Result_4_fu_240_p4();
    void thread_p_Result_5_fu_255_p4();
    void thread_p_Result_6_fu_270_p4();
    void thread_p_Result_s_fu_180_p4();
    void thread_r_V_fu_165_p2();
    void thread_ret_V_5_fu_349_p2();
    void thread_ret_V_6_fu_363_p2();
    void thread_rhs_V_5_fu_359_p1();
    void thread_rhs_V_6_fu_373_p1();
    void thread_rhs_V_fu_345_p1();
    void thread_trunc_ln681_fu_171_p1();
    void thread_xor_ln769_fu_159_p2();
    void thread_zext_ln18_1_fu_190_p1();
    void thread_zext_ln18_fu_175_p1();
    void thread_zext_ln19_1_fu_220_p1();
    void thread_zext_ln19_fu_205_p1();
    void thread_zext_ln20_1_fu_250_p1();
    void thread_zext_ln20_fu_235_p1();
    void thread_zext_ln215_1_fu_289_p1();
    void thread_zext_ln215_2_fu_299_p1();
    void thread_zext_ln215_3_fu_303_p1();
    void thread_zext_ln215_4_fu_313_p1();
    void thread_zext_ln215_5_fu_317_p1();
    void thread_zext_ln215_6_fu_327_p1();
    void thread_zext_ln215_7_fu_331_p1();
    void thread_zext_ln215_fu_285_p1();
    void thread_zext_ln21_1_fu_280_p1();
    void thread_zext_ln21_fu_265_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
