// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu (
        ap_clk,
        ap_rst,
        norm_V,
        shiftx_V,
        shifty_V,
        weight_V,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [13:0] norm_V;
input  [10:0] shiftx_V;
input  [10:0] shifty_V;
input  [10:0] weight_V;
output  [13:0] ap_return;
input   ap_ce;

reg[13:0] ap_return;

reg  signed [10:0] weight_V_read_reg_567;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [10:0] shifty_V_read_reg_572;
wire  signed [13:0] p_Val2_10_fu_180_p3;
reg  signed [13:0] p_Val2_10_reg_578;
wire   [0:0] icmp_ln1494_fu_188_p2;
reg   [0:0] icmp_ln1494_reg_586;
reg   [0:0] icmp_ln1494_reg_586_pp0_iter2_reg;
reg   [0:0] p_Result_2_reg_593;
reg   [0:0] p_Result_2_reg_593_pp0_iter2_reg;
wire   [13:0] p_Val2_12_fu_225_p2;
reg   [13:0] p_Val2_12_reg_600;
reg   [13:0] p_Val2_12_reg_600_pp0_iter2_reg;
reg   [0:0] p_Result_3_reg_606;
reg   [0:0] p_Result_3_reg_606_pp0_iter2_reg;
wire  signed [24:0] grp_fu_557_p3;
reg  signed [24:0] ret_V_6_reg_613;
reg   [0:0] p_Result_4_reg_622;
reg   [0:0] tmp_reg_628;
wire   [13:0] p_Val2_16_fu_288_p2;
reg   [13:0] p_Val2_16_reg_633;
wire   [0:0] underflow_2_fu_440_p2;
reg   [0:0] underflow_2_reg_639;
wire   [0:0] or_ln340_23_fu_445_p2;
reg   [0:0] or_ln340_23_reg_644;
wire   [0:0] and_ln340_2_fu_468_p2;
reg   [0:0] and_ln340_2_reg_649;
wire  signed [13:0] lhs_V_fu_86_p0;
wire    ap_block_pp0_stage0;
wire  signed [11:0] rhs_V_fu_90_p3;
wire  signed [14:0] lhs_V_fu_86_p1;
wire  signed [14:0] sext_ln728_fu_98_p1;
wire   [14:0] ret_V_fu_106_p2;
wire  signed [13:0] tmp_V_fu_120_p0;
wire  signed [13:0] sext_ln1192_fu_102_p1;
wire   [13:0] tmp_V_fu_120_p2;
wire   [0:0] p_Result_1_fu_126_p3;
wire   [0:0] p_Result_s_fu_112_p3;
wire   [0:0] xor_ln786_fu_134_p2;
wire   [0:0] xor_ln340_fu_152_p2;
wire   [0:0] xor_ln340_209_fu_146_p2;
wire   [0:0] underflow_fu_140_p2;
wire   [0:0] or_ln340_21_fu_158_p2;
wire   [13:0] select_ln340_fu_164_p3;
wire   [13:0] select_ln388_fu_172_p3;
wire  signed [11:0] rhs_V_6_fu_196_p3;
wire   [14:0] lhs_V_5_fu_193_p1;
wire  signed [14:0] sext_ln728_128_fu_203_p1;
wire   [14:0] ret_V_5_fu_211_p2;
wire  signed [13:0] sext_ln1192_128_fu_207_p1;
wire  signed [18:0] rhs_V_7_fu_244_p3;
wire   [13:0] p_Val2_15_fu_269_p4;
wire   [13:0] zext_ln415_fu_285_p1;
wire   [0:0] tmp_706_fu_294_p3;
wire   [0:0] p_Result_5_fu_278_p3;
wire   [0:0] xor_ln416_fu_302_p2;
wire   [2:0] tmp_1_fu_322_p4;
wire   [3:0] tmp_2_fu_337_p4;
wire   [0:0] carry_1_fu_308_p2;
wire   [0:0] Range1_all_ones_fu_346_p2;
wire   [0:0] Range1_all_zeros_fu_352_p2;
wire   [0:0] tmp_708_fu_366_p3;
wire   [0:0] Range2_all_ones_fu_331_p2;
wire   [0:0] xor_ln779_fu_373_p2;
wire   [0:0] and_ln779_fu_379_p2;
wire   [0:0] deleted_zeros_fu_358_p3;
wire   [0:0] p_Result_6_fu_314_p3;
wire   [0:0] xor_ln785_9_fu_399_p2;
wire   [0:0] or_ln785_7_fu_405_p2;
wire   [0:0] xor_ln785_10_fu_411_p2;
wire   [0:0] deleted_ones_fu_385_p3;
wire   [0:0] and_ln781_fu_393_p2;
wire   [0:0] and_ln786_fu_422_p2;
wire   [0:0] or_ln786_fu_428_p2;
wire   [0:0] xor_ln786_161_fu_434_p2;
wire   [0:0] overflow_fu_416_p2;
wire   [0:0] or_ln340_319_fu_451_p2;
wire   [0:0] or_ln340_320_fu_457_p2;
wire   [0:0] xor_ln1494_fu_463_p2;
wire   [0:0] xor_ln786_6_fu_474_p2;
wire   [0:0] xor_ln340_162_fu_488_p2;
wire   [0:0] xor_ln340_210_fu_484_p2;
wire   [0:0] underflow_1_fu_479_p2;
wire   [0:0] and_ln340_fu_524_p2;
wire   [13:0] select_ln388_161_fu_505_p3;
wire   [13:0] select_ln388_162_fu_518_p3;
wire   [0:0] or_ln340_fu_493_p2;
wire   [0:0] and_ln340_1_fu_537_p2;
wire   [13:0] select_ln340_162_fu_498_p3;
wire   [13:0] select_ln340_289_fu_529_p3;
wire   [13:0] select_ln340_163_fu_512_p3;
wire   [13:0] select_ln340_290_fu_542_p3;
wire   [13:0] select_ln340_291_fu_550_p3;
reg    ap_ce_reg;
reg   [13:0] norm_V_int_reg;
reg   [10:0] shiftx_V_int_reg;
reg   [10:0] shifty_V_int_reg;
reg   [10:0] weight_V_int_reg;
reg   [13:0] ap_return_int_reg;

FracNet_mac_muladmb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 25 ))
FracNet_mac_muladmb6_U555(
    .din0(weight_V_read_reg_567),
    .din1(p_Val2_10_reg_578),
    .din2(rhs_V_7_fu_244_p3),
    .dout(grp_fu_557_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln340_2_reg_649 <= and_ln340_2_fu_468_p2;
        icmp_ln1494_reg_586 <= icmp_ln1494_fu_188_p2;
        icmp_ln1494_reg_586_pp0_iter2_reg <= icmp_ln1494_reg_586;
        or_ln340_23_reg_644 <= or_ln340_23_fu_445_p2;
        p_Result_2_reg_593 <= ret_V_5_fu_211_p2[32'd14];
        p_Result_2_reg_593_pp0_iter2_reg <= p_Result_2_reg_593;
        p_Result_3_reg_606 <= p_Val2_12_fu_225_p2[32'd13];
        p_Result_3_reg_606_pp0_iter2_reg <= p_Result_3_reg_606;
        p_Result_4_reg_622 <= grp_fu_557_p3[32'd24];
        p_Val2_10_reg_578 <= p_Val2_10_fu_180_p3;
        p_Val2_12_reg_600 <= p_Val2_12_fu_225_p2;
        p_Val2_12_reg_600_pp0_iter2_reg <= p_Val2_12_reg_600;
        p_Val2_16_reg_633 <= p_Val2_16_fu_288_p2;
        ret_V_6_reg_613 <= grp_fu_557_p3;
        shifty_V_read_reg_572 <= shifty_V_int_reg;
        tmp_reg_628 <= grp_fu_557_p3[32'd6];
        underflow_2_reg_639 <= underflow_2_fu_440_p2;
        weight_V_read_reg_567 <= weight_V_int_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln340_291_fu_550_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        norm_V_int_reg <= norm_V;
        shiftx_V_int_reg <= shiftx_V;
        shifty_V_int_reg <= shifty_V;
        weight_V_int_reg <= weight_V;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln340_291_fu_550_p3;
    end
end

assign Range1_all_ones_fu_346_p2 = ((tmp_2_fu_337_p4 == 4'd15) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_352_p2 = ((tmp_2_fu_337_p4 == 4'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_331_p2 = ((tmp_1_fu_322_p4 == 3'd7) ? 1'b1 : 1'b0);

assign and_ln340_1_fu_537_p2 = (or_ln340_fu_493_p2 & icmp_ln1494_reg_586_pp0_iter2_reg);

assign and_ln340_2_fu_468_p2 = (xor_ln1494_fu_463_p2 & or_ln340_320_fu_457_p2);

assign and_ln340_fu_524_p2 = (underflow_1_fu_479_p2 & icmp_ln1494_reg_586_pp0_iter2_reg);

assign and_ln779_fu_379_p2 = (xor_ln779_fu_373_p2 & Range2_all_ones_fu_331_p2);

assign and_ln781_fu_393_p2 = (carry_1_fu_308_p2 & Range1_all_ones_fu_346_p2);

assign and_ln786_fu_422_p2 = (p_Result_6_fu_314_p3 & deleted_ones_fu_385_p3);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign carry_1_fu_308_p2 = (xor_ln416_fu_302_p2 & p_Result_5_fu_278_p3);

assign deleted_ones_fu_385_p3 = ((carry_1_fu_308_p2[0:0] === 1'b1) ? and_ln779_fu_379_p2 : Range1_all_ones_fu_346_p2);

assign deleted_zeros_fu_358_p3 = ((carry_1_fu_308_p2[0:0] === 1'b1) ? Range1_all_ones_fu_346_p2 : Range1_all_zeros_fu_352_p2);

assign icmp_ln1494_fu_188_p2 = (($signed(p_Val2_10_reg_578) > $signed(14'd0)) ? 1'b1 : 1'b0);

assign lhs_V_5_fu_193_p1 = $unsigned(p_Val2_10_reg_578);

assign lhs_V_fu_86_p0 = norm_V_int_reg;

assign lhs_V_fu_86_p1 = lhs_V_fu_86_p0;

assign or_ln340_21_fu_158_p2 = (xor_ln340_fu_152_p2 | p_Result_1_fu_126_p3);

assign or_ln340_23_fu_445_p2 = (underflow_2_fu_440_p2 | overflow_fu_416_p2);

assign or_ln340_319_fu_451_p2 = (xor_ln785_10_fu_411_p2 | and_ln786_fu_422_p2);

assign or_ln340_320_fu_457_p2 = (or_ln340_319_fu_451_p2 | and_ln781_fu_393_p2);

assign or_ln340_fu_493_p2 = (xor_ln340_162_fu_488_p2 | p_Result_3_reg_606_pp0_iter2_reg);

assign or_ln785_7_fu_405_p2 = (xor_ln785_9_fu_399_p2 | p_Result_6_fu_314_p3);

assign or_ln786_fu_428_p2 = (and_ln786_fu_422_p2 | and_ln781_fu_393_p2);

assign overflow_fu_416_p2 = (xor_ln785_10_fu_411_p2 & or_ln785_7_fu_405_p2);

assign p_Result_1_fu_126_p3 = tmp_V_fu_120_p2[32'd13];

assign p_Result_5_fu_278_p3 = ret_V_6_reg_613[32'd20];

assign p_Result_6_fu_314_p3 = p_Val2_16_fu_288_p2[32'd13];

assign p_Result_s_fu_112_p3 = ret_V_fu_106_p2[32'd14];

assign p_Val2_10_fu_180_p3 = ((or_ln340_21_fu_158_p2[0:0] === 1'b1) ? select_ln340_fu_164_p3 : select_ln388_fu_172_p3);

assign p_Val2_12_fu_225_p2 = ($signed(sext_ln1192_128_fu_207_p1) + $signed(p_Val2_10_reg_578));

assign p_Val2_15_fu_269_p4 = {{ret_V_6_reg_613[20:7]}};

assign p_Val2_16_fu_288_p2 = (p_Val2_15_fu_269_p4 + zext_ln415_fu_285_p1);

assign ret_V_5_fu_211_p2 = ($signed(lhs_V_5_fu_193_p1) + $signed(sext_ln728_128_fu_203_p1));

assign ret_V_fu_106_p2 = ($signed(lhs_V_fu_86_p1) + $signed(sext_ln728_fu_98_p1));

assign rhs_V_6_fu_196_p3 = {{shifty_V_read_reg_572}, {1'd0}};

assign rhs_V_7_fu_244_p3 = {{shifty_V_read_reg_572}, {8'd0}};

assign rhs_V_fu_90_p3 = {{shiftx_V_int_reg}, {1'd0}};

assign select_ln340_162_fu_498_p3 = ((xor_ln340_210_fu_484_p2[0:0] === 1'b1) ? 14'd8191 : p_Val2_12_reg_600_pp0_iter2_reg);

assign select_ln340_163_fu_512_p3 = ((or_ln340_23_reg_644[0:0] === 1'b1) ? 14'd8191 : p_Val2_16_reg_633);

assign select_ln340_289_fu_529_p3 = ((and_ln340_fu_524_p2[0:0] === 1'b1) ? select_ln388_161_fu_505_p3 : select_ln388_162_fu_518_p3);

assign select_ln340_290_fu_542_p3 = ((and_ln340_1_fu_537_p2[0:0] === 1'b1) ? select_ln340_162_fu_498_p3 : select_ln340_289_fu_529_p3);

assign select_ln340_291_fu_550_p3 = ((and_ln340_2_reg_649[0:0] === 1'b1) ? select_ln340_163_fu_512_p3 : select_ln340_290_fu_542_p3);

assign select_ln340_fu_164_p3 = ((xor_ln340_209_fu_146_p2[0:0] === 1'b1) ? 14'd8191 : tmp_V_fu_120_p2);

assign select_ln388_161_fu_505_p3 = ((underflow_1_fu_479_p2[0:0] === 1'b1) ? 14'd8192 : p_Val2_12_reg_600_pp0_iter2_reg);

assign select_ln388_162_fu_518_p3 = ((underflow_2_reg_639[0:0] === 1'b1) ? 14'd8192 : p_Val2_16_reg_633);

assign select_ln388_fu_172_p3 = ((underflow_fu_140_p2[0:0] === 1'b1) ? 14'd8192 : tmp_V_fu_120_p2);

assign sext_ln1192_128_fu_207_p1 = rhs_V_6_fu_196_p3;

assign sext_ln1192_fu_102_p1 = rhs_V_fu_90_p3;

assign sext_ln728_128_fu_203_p1 = rhs_V_6_fu_196_p3;

assign sext_ln728_fu_98_p1 = rhs_V_fu_90_p3;

assign tmp_1_fu_322_p4 = {{ret_V_6_reg_613[24:22]}};

assign tmp_2_fu_337_p4 = {{ret_V_6_reg_613[24:21]}};

assign tmp_706_fu_294_p3 = p_Val2_16_fu_288_p2[32'd13];

assign tmp_708_fu_366_p3 = ret_V_6_reg_613[32'd21];

assign tmp_V_fu_120_p0 = norm_V_int_reg;

assign tmp_V_fu_120_p2 = ($signed(tmp_V_fu_120_p0) + $signed(sext_ln1192_fu_102_p1));

assign underflow_1_fu_479_p2 = (xor_ln786_6_fu_474_p2 & p_Result_2_reg_593_pp0_iter2_reg);

assign underflow_2_fu_440_p2 = (xor_ln786_161_fu_434_p2 & p_Result_4_reg_622);

assign underflow_fu_140_p2 = (xor_ln786_fu_134_p2 & p_Result_s_fu_112_p3);

assign xor_ln1494_fu_463_p2 = (icmp_ln1494_reg_586 ^ 1'd1);

assign xor_ln340_162_fu_488_p2 = (p_Result_2_reg_593_pp0_iter2_reg ^ 1'd1);

assign xor_ln340_209_fu_146_p2 = (p_Result_s_fu_112_p3 ^ p_Result_1_fu_126_p3);

assign xor_ln340_210_fu_484_p2 = (p_Result_3_reg_606_pp0_iter2_reg ^ p_Result_2_reg_593_pp0_iter2_reg);

assign xor_ln340_fu_152_p2 = (p_Result_s_fu_112_p3 ^ 1'd1);

assign xor_ln416_fu_302_p2 = (tmp_706_fu_294_p3 ^ 1'd1);

assign xor_ln779_fu_373_p2 = (tmp_708_fu_366_p3 ^ 1'd1);

assign xor_ln785_10_fu_411_p2 = (p_Result_4_reg_622 ^ 1'd1);

assign xor_ln785_9_fu_399_p2 = (deleted_zeros_fu_358_p3 ^ 1'd1);

assign xor_ln786_161_fu_434_p2 = (or_ln786_fu_428_p2 ^ 1'd1);

assign xor_ln786_6_fu_474_p2 = (p_Result_3_reg_606_pp0_iter2_reg ^ 1'd1);

assign xor_ln786_fu_134_p2 = (p_Result_1_fu_126_p3 ^ 1'd1);

assign zext_ln415_fu_285_p1 = tmp_reg_628;

endmodule //relu
